<a href="https://colab.research.google.com/github/LOPAMUDRA-MUKHERJEE/DataSC/blob/main/practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/bipulshahi/Dataset/main/customer_churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [7]:
df1= df.drop('customerID',axis='columns')
df1.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [8]:
df1.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
def fix_total_charges(charges):
  try:
    return float(charges)
  except:
    return np.nan

In [13]:
df1['TotalCharges'] = df1['TotalCharges'].apply(fix_total_charges)

In [14]:
df1.isna().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [15]:
df1['TotalCharges']= df1['TotalCharges'].fillna(df1['TotalCharges'].mean())

In [16]:
df1.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [18]:
df1.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
df1.nunique()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [20]:
print(df1['MultipleLines'].unique())
print(df1['InternetService'].unique())
print(df1['OnlineSecurity'].unique())
print(df1['OnlineBackup'].unique())
print(df1['DeviceProtection'].unique())
print(df1['TechSupport'].unique())
print(df1['StreamingTV'].unique())
print(df1['StreamingMovies'].unique())
print(df1['Contract'].unique())
print(df1['PaymentMethod'].unique())


['No phone service' 'No' 'Yes']
['DSL' 'Fiber optic' 'No']
['No' 'Yes' 'No internet service']
['Yes' 'No' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['Month-to-month' 'One year' 'Two year']
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']


In [25]:
def comnine_categories(text):
  if text in ["No", "No phone service","No internet service"]:
    return "No"
    slef
  else:
    return text
    # else:
    # return text

In [26]:
df1['MultipleLines'] = df1['MultipleLines'].apply(comnine_categories)
df1['InternetService'] = df1['InternetService'].apply(comnine_categories)
df1['OnlineSecurity'] = df1['OnlineSecurity'].apply(comnine_categories)
df1['OnlineBackup'] = df1['OnlineBackup'].apply(comnine_categories)
df1['DeviceProtection'] = df1['DeviceProtection'].apply(comnine_categories)
df1['TechSupport'] = df1['TechSupport'].apply(comnine_categories)
df1['StreamingTV'] = df1['StreamingTV'].apply(comnine_categories)
df1['StreamingMovies'] = df1['StreamingMovies'].apply(comnine_categories)
df1['Contract'] = df1['Contract'].apply(comnine_categories)
df1['PaymentMethod'] = df1['PaymentMethod'].apply(comnine_categories)

In [27]:
print(df1['MultipleLines'].unique())
print(df1['InternetService'].unique())
print(df1['OnlineSecurity'].unique())
print(df1['OnlineBackup'].unique())
print(df1['DeviceProtection'].unique())
print(df1['TechSupport'].unique())
print(df1['StreamingTV'].unique())
print(df1['StreamingMovies'].unique())
print(df1['Contract'].unique())
print(df1['PaymentMethod'].unique())

['No' 'Yes']
['DSL' 'Fiber optic' 'No']
['No' 'Yes']
['Yes' 'No']
['No' 'Yes']
['No' 'Yes']
['No' 'Yes']
['No' 'Yes']
['Month-to-month' 'One year' 'Two year']
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']


***label encoding ***


In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df1['MultipleLines'] = le.fit_transform(df1['MultipleLines'])
df1['OnlineSecurity'] = le.fit_transform(df1['OnlineSecurity'])
df1['OnlineBackup'] = le.fit_transform(df1['OnlineBackup'])
df1['DeviceProtection'] = le.fit_transform(df1['DeviceProtection'])
df1['TechSupport'] = le.fit_transform(df1['TechSupport'])
df1['StreamingTV'] = le.fit_transform(df1['StreamingTV'])
df1['StreamingMovies'] = le.fit_transform(df1['StreamingMovies'])
df1['gender'] = le.fit_transform(df1['gender'])
df1['Partner'] = le.fit_transform(df1['Partner'])
df1['Dependents'] = le.fit_transform(df1['Dependents'])
df1['PhoneService'] = le.fit_transform(df1['PhoneService'])
df1['PaperlessBilling'] = le.fit_transform(df1['PaperlessBilling'])
df1['Contract'] = le.fit_transform(df1['Contract'])
df1['PaymentMethod'] = le.fit_transform(df1['PaymentMethod'])
df1['InternetService'] = le.fit_transform(df1['InternetService'])
df1['Churn'] = le.fit_transform(df1['Churn'])

In [32]:
df1.tail()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
7038              1                0               1             0   
7039              1                1               0             1   
7040              0                0               1             0   
7041              1                1               0             0   
7042              0                1               1             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
7038                 1            1            1                1         1   
7039                 1            0            1                1         1   
7040                 0            0            0                0         0   
7041                 0            0            0                0         0   
7042                 1            1            1                1         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
7038                 1              3           84.80       1990.50      0  
7039                 1              1          103.20       7362.90      0  
7040                 1              2           29.60        346.45      0  
7041                 1              3           74.40        306.60      1  
7042                 1              0          105.65       6844.50      0

In [33]:
df1.dtypes

gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [35]:
print(df1['InternetService'].unique())
print(df1['Contract'].unique())
print(df1['PaymentMethod'].unique())

[0 1 2]
[0 1 2]
[2 3 0 1]


**One Hot Encoding**

In [36]:
df2 = pd.get_dummies(df1, columns= ['InternetService','Contract','PaymentMethod'])
df2.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  OnlineSecurity  OnlineBackup  DeviceProtection  ...  \
0              0               0             1                 0  ...   
1              0               1             0                 1  ...   
2              0               1             1                 0  ...   
3              0               1             0                 1  ...   
4              0               0             0                 0  ...   

   InternetService_0  InternetService_1  InternetService_2  Contract_0  \
0               True              False              False        True   
1               True              False              False       False   
2               True              False              False        True   
3               True              False              False       False   
4              False               True              False        True   

   Contract_1  Contract_2  PaymentMethod_0  PaymentMethod_1  PaymentMethod_2  \
0       False       False            False            False             True   
1        True       False            False            False            False   
2       False       False            False            False            False   
3        True       False             True            False            False   
4       False       False            False            False             True   

   PaymentMethod_3  
0            False  
1             True  
2             True  
3            False  
4            False  

[5 rows x 27 columns]

***Machine Learning ***

In [37]:
x= df2.drop('Churn', axis='columns')
y= df2['Churn']

In [38]:
y.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

Undersampling to decrease sample size in category 0 to create a balanced distribution

In [39]:
from imblearn.under_sampling import RandomUnderSampler
rus= RandomUnderSampler(random_state=42)
Xu, Yu = rus.fit_resample(x,y)

In [40]:
Yu.value_counts()

Churn
0    1869
1    1869
Name: count, dtype: int64

Oversampling to increase sample size in category 1 to create a balanced distribution


In [41]:
from imblearn.over_sampling import RandomOverSampler
sm = RandomOverSampler(random_state=42)
Xo, Yo = sm.fit_resample(x,y)

In [42]:
Yo.value_counts()

Churn
0    5174
1    5174
Name: count, dtype: int64

SMOTE
Synthetic Minority Oversampling Technique Estimation

In [44]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
Xsm, Ysm = smote.fit_resample(x,y)

Ysm.value_counts()

Churn
0    5174
1    5174
Name: count, dtype: int64

Split

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Xsm, Ysm, test_size=0.2, random_state=42)

Data Scaling

In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_trainScaled = scaler.fit_transform(X_train)
X_testScaled = scaler.transform(X_test)

In [48]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

Create model instances


In [49]:
model1 = KNeighborsClassifier(n_neighbors= 5)
model2 = DecisionTreeClassifier(max_depth=4)
model3 = RandomForestClassifier(max_depth=4)

Train the models on the scaled training data


In [52]:
model1.fit(X_trainScaled, y_train)
model2.fit(X_trainScaled, y_train)
model3.fit(X_trainScaled, y_train)

DecisionTreeClassifier(max_depth=4)

In [53]:
print("Evaluation mertrics for KNN")
print("Accuracy on training data =", model1.score(X_trainScaled, y_train))
print("Accuracy on test data =", model1.score(X_testScaled, y_test))

Evaluation mertrics for KNN
Accuracy on training data = 0.8726745590722397
Accuracy on test data = 0.8289855072463768


In [54]:
print("Evaluation mertrics for DecisionTree")
print("Accuracy on training data =", model2.score(X_trainScaled, y_train))
print("Accuracy on test data =", model2.score(X_testScaled, y_test))

Evaluation mertrics for DecisionTree
Accuracy on training data = 0.8035757429330757
Accuracy on test data = 0.8043478260869565


In [55]:
print("Evaluation mertrics for RandomForest")
print("Accuracy on training data =", model3.score(X_trainScaled, y_train))
print("Accuracy on test data =", model3.score(X_testScaled, y_test))

Evaluation mertrics for RandomForest
Accuracy on training data = 0.8190384150761053
Accuracy on test data = 0.8227053140096618


Evaluate peformance for each category

In [56]:
df2['Churn'].unique()

array([0, 1])

In [57]:
df2['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [59]:
from sklearn.metrics import confusion_matrix, classification_report

KNN

In [63]:
confusion_matrix(y_train, model1.predict(X_trainScaled))

array([[3522,  631],
       [ 423, 3702]])

In [64]:
print(classification_report(y_train, model1.predict(X_trainScaled)))

              precision    recall  f1-score   support

           0       0.89      0.85      0.87      4153
           1       0.85      0.90      0.88      4125

    accuracy                           0.87      8278
   macro avg       0.87      0.87      0.87      8278
weighted avg       0.87      0.87      0.87      8278



In [65]:
confusion_matrix(y_test, model1.predict(X_testScaled))

array([[834, 187],
       [167, 882]])

In [66]:
print(classification_report(y_test, model1.predict(X_testScaled)))

              precision    recall  f1-score   support

           0       0.83      0.82      0.82      1021
           1       0.83      0.84      0.83      1049

    accuracy                           0.83      2070
   macro avg       0.83      0.83      0.83      2070
weighted avg       0.83      0.83      0.83      2070



Decision Tree

In [67]:
print(classification_report(y_train, model2.predict(X_trainScaled)))

              precision    recall  f1-score   support

           0       0.82      0.77      0.80      4153
           1       0.79      0.83      0.81      4125

    accuracy                           0.80      8278
   macro avg       0.80      0.80      0.80      8278
weighted avg       0.80      0.80      0.80      8278



Random Forest

In [68]:
print(classification_report(y_train, model3.predict(X_trainScaled)))

              precision    recall  f1-score   support

           0       0.86      0.76      0.81      4153
           1       0.78      0.88      0.83      4125

    accuracy                           0.82      8278
   macro avg       0.82      0.82      0.82      8278
weighted avg       0.82      0.82      0.82      8278



use model to make predictions

In [69]:
X_testScaled[4]

array([1.        , 0.        , 0.        , 0.        , 0.80555556,
       1.        , 1.        , 0.        , 0.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.85970149,
       0.71655313, 0.        , 1.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        ])

In [70]:
print(model1.predict([X_testScaled[4]]))
print(model2.predict([X_testScaled[4]]))
print(model3.predict([X_testScaled[4]]))

[1]
[0]
[0]


In [71]:
print(y_test.values[4])

1


Save model

In [72]:
import pickle

In [74]:
with open('model_1.pkl','wb') as f:
    pickle.dump(model1,f)

In [75]:
with open('model_2.pkl','wb') as f:
    pickle.dump(model2,f)

In [76]:
with open('model_3.pkl','wb') as f:
    pickle.dump(model3,f)